// @test error

fn main() : int
{
	3 = 4;
	return 4;
}