// @test error

fn foo() : bar
{
	return 1;
}

fn main() : int
{
	return 2;
}