// @test error

fn main()
{
	return 2;
}