// @test error

fn foo(int x)
{
	return x;
}

fn main()
{
	return foo(4, 4);
}