// @test error

fn main()
{
	return foo;
}