// @test error

fn main() : int
{
	return foo;
}