// @test error

fn main() : int
{
    int y = x;
    int x = 2;
    return 4;
}
