// @test error

fn main() : int
{
	foo = 3;
	return 0;
}